# Generated by Django 3.2.7 on 2021-09-17 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteXxi',
            fields=[
                ('id_cliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=30)),
                ('correo_cli', models.CharField(max_length=30)),
                ('telefono_cli', models.BigIntegerField()),
                ('direccion_cli', models.CharField(blank=True, max_length=50, null=True)),
                ('contrasena_cli', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientesXxi',
            fields=[
                ('id_ingrediente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ingrediente', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=12)),
                ('cantidad', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MesaXxi',
            fields=[
                ('id_mesa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('capacidad', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenesXxi',
            fields=[
                ('id_orden', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('pagado', models.CharField(max_length=1)),
                ('detalle', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=12)),
                ('cliente_xxi_id_cliente', models.ForeignKey(db_column='cliente_xxi_id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='main.clientexxi')),
                ('mesa_xxi_id_mesa', models.ForeignKey(db_column='mesa_xxi_id_mesa', on_delete=django.db.models.deletion.DO_NOTHING, to='main.mesaxxi')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedoresXxi',
            fields=[
                ('id_proveedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=15)),
                ('telefono', models.BigIntegerField()),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpladoXxi',
            fields=[
                ('id_tipo_empleado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_empleado', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPagoXxi',
            fields=[
                ('id_tipo_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProductoXxi',
            fields=[
                ('id_tipo_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ReservasXxi',
            fields=[
                ('id_reserva', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateField()),
                ('cliente_xxi_id_cliente', models.ForeignKey(db_column='cliente_xxi_id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='main.clientexxi')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosXxi',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('precio', models.BigIntegerField()),
                ('tipo_producto_xxi_id_tipo_producto', models.ForeignKey(db_column='tipo_producto_xxi_id_tipo_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='main.tipoproductoxxi')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaXxi',
            fields=[
                ('id_factura', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.BigIntegerField()),
                ('cliente_xxi_id_cliente', models.ForeignKey(db_column='cliente_xxi_id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='main.clientexxi')),
                ('tipo_pago_xxi_id_tipo_pago', models.ForeignKey(db_column='tipo_pago_xxi_id_tipo_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='main.tipopagoxxi')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadosXxi',
            fields=[
                ('id_empleado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_emp', models.CharField(max_length=15)),
                ('apellido_pat_emp', models.CharField(max_length=15)),
                ('apellido_mat_emp', models.CharField(max_length=15)),
                ('salario', models.BigIntegerField()),
                ('fecha_nac', models.DateField()),
                ('direccion_emp', models.CharField(max_length=30)),
                ('telefono_emp', models.BigIntegerField()),
                ('correo_emp', models.CharField(max_length=30)),
                ('contrasena_emp', models.CharField(max_length=12)),
                ('tipo_emplado_xxi_id_tipo_empleado', models.ForeignKey(db_column='tipo_emplado_xxi_id_tipo_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='main.tipoempladoxxi')),
            ],
        ),
        migrations.CreateModel(
            name='Relation8',
            fields=[
                ('cliente_xxi_id_cliente', models.OneToOneField(db_column='cliente_xxi_id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.clientexxi')),
                ('ordenes_xxi_id_orden', models.ForeignKey(db_column='ordenes_xxi_id_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='main.ordenesxxi')),
            ],
        ),
        migrations.CreateModel(
            name='Relation33',
            fields=[
                ('ingredientes_xxi_id_ingrediente', models.OneToOneField(db_column='ingredientes_xxi_id_ingrediente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.ingredientesxxi')),
                ('proveedores_xxi_id_proveedor', models.ForeignKey(db_column='proveedores_xxi_id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='main.proveedoresxxi')),
            ],
        ),
        migrations.CreateModel(
            name='Relation32',
            fields=[
                ('productos_xxi_id_producto', models.OneToOneField(db_column='productos_xxi_id_producto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.productosxxi')),
                ('ordenes_xxi_id_orden', models.ForeignKey(db_column='ordenes_xxi_id_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='main.ordenesxxi')),
            ],
        ),
        migrations.CreateModel(
            name='Relation31',
            fields=[
                ('productos_xxi_id_producto', models.OneToOneField(db_column='productos_xxi_id_producto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.productosxxi')),
                ('ingredientes_xxi_id_ingrediente', models.ForeignKey(db_column='ingredientes_xxi_id_ingrediente', on_delete=django.db.models.deletion.DO_NOTHING, to='main.ingredientesxxi')),
            ],
        ),
        migrations.CreateModel(
            name='Relation3',
            fields=[
                ('empleados_xxi_id_empleado', models.OneToOneField(db_column='empleados_xxi_id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.empleadosxxi')),
                ('ordenes_xxi_id_orden', models.ForeignKey(db_column='ordenes_xxi_id_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='main.ordenesxxi')),
            ],
        ),
        migrations.CreateModel(
            name='Relation13',
            fields=[
                ('cliente_xxi_id_cliente', models.OneToOneField(db_column='cliente_xxi_id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.clientexxi')),
                ('reservas_xxi_id_reserva', models.ForeignKey(db_column='reservas_xxi_id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='main.reservasxxi')),
            ],
        ),
        migrations.CreateModel(
            name='Relation12',
            fields=[
                ('mesa_xxi_id_mesa', models.OneToOneField(db_column='mesa_xxi_id_mesa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.mesaxxi')),
                ('cliente_xxi_id_cliente', models.ForeignKey(db_column='cliente_xxi_id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='main.clientexxi')),
            ],
        ),
        migrations.CreateModel(
            name='Relation10',
            fields=[
                ('ordenes_xxi_id_orden', models.OneToOneField(db_column='ordenes_xxi_id_orden', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.ordenesxxi')),
                ('factura_xxi_id_factura', models.ForeignKey(db_column='factura_xxi_id_factura', on_delete=django.db.models.deletion.DO_NOTHING, to='main.facturaxxi')),
            ],
        ),
    ]
